site_name: Beastiary
theme:
  name: material
  logo: images/Beastiary.png
  palette:
    primary: teal
    accent: orange
repo_name: wytamma/beastiary
repo_url: https://github.com/wytamma/beastiary
nav:
- Home: index.md
- Tutorial - User Guide:
  - tutorial/index.md
  - tutorial/first-steps.md
  - tutorial/logs-from-the-command-line.md
  - tutorial/log-file-format.md
  - tutorial/remote-beastiary.md
  - tutorial/security.md
  - tutorial/google-colab.md
  - tutorial/running-in-the-background.md
- Plots:
  - plots/pairwise.md
  - plots/Cumulative-ESS.md
  - plots/parallel-coordinates.md
- Design and Implementation: design.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- md_in_html
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js